### ISSUE TITLE
Cannot use age command

### ISSUE THREAD

**Issue by Jackiecrazy** [TheDrOfDoctoring/Vampiric-Ageing#1]
The age command takes your age as `age` but then tries to read the `level` argument.

**Comment by TheDrOfDoctoring** [comment]
Thanks for the report, previously the command should still have worked as long as you were only specifying yourself as the target for it since I was using it in dev for that purpose. 

With this, i've also improved the handling for it so it should give more information if the command isn't used correctly as before it would provide no information about why the command had failed.
