### ISSUE TITLE
Vampiric Ageing & Step Assist & Werewolves

### ISSUE THREAD

**Issue by shellos33** [TheDrOfDoctoring/Vampiric-Ageing#3]
I've been playing on a LAN server with my friend, we've got Vampiric Ageing & Werewolves. I'm playing as a werewolf, my friend is playing as a vampire. I'm a age 3 (wolf) and he's at age level 4 (vamp). The config has step assist set to 0, but step assist is still active.

As a werewolf, I'm also having issues where I can't automatically walk up 1/16 (0.0625) to 1/2 (0.5) blocks (grass paths and slabs/stairs respectively) until I swap between survivalist mode and back again. This will fix the issue for an undetermined amount of time. The issue will start up again eventually and I've yet to figure out what triggers that.

I'm fairly certain that the issue for both of these problems lies in step assist, but I've yet to see if it's reliant on the werewolf mod being installed as well. It is of note that the issue with werewolf happens whether or not I have climber or leap selected on my skill tree. I have yet to test if it still happens if I have yet to pick an option there.

**Comment by TheDrOfDoctoring** [comment]
Thanks for the report, I'm assuming this issue is happening on the Minecraft 1.16 version of the mod as step assist is handled differently there, leading to some issues. Should now be fixed with the [latest release for 1.16.5 ](https://legacy.curseforge.com/minecraft/mc-mods/vampiric-ageing-a-vampirism-addon/files/4817646), if not please respond here.
